spring:
  profiles:
    active: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}/bundle-network?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&connectionCollation=utf8_general_ci
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    idle-timeout: ${IDLE_TIMEOUT:10}
    minimum-idle: ${MINIMUM_IDLE:0}
    maximum-pool-size: ${MAXIMUM_POOL_SIZE:10}
    connection-timeout: ${CONNECTION_TIMEOUT:2000}
    max-lifetime: ${MAX_LIFETIME:0}

executor:
  core-pool-size: ${EXECUTOR_CORE_POOL_SIZE:10}
  max-pool-size: ${EXECUTOR_MAX_POOL_SIZE:100}
  queue-capacity: ${EXECUTOR_QUEUE_CAPACITY:100}

auth:
  jwt:
    exp-minute: ${AUTH_JWT_EXP_MINUTE:86400}
    secret: ${AUTH_JWT_SECRET}

server:
  port: ${SERVER_PORT}
